const items = [
  {
    id_item: 0,
    name: "Coca Cola 355ml",
    price: 16,
    picture: "/assets/Seven_CocaCola.jpeg",
    details: "",
    store: "7 Eleven",
    categories: [],
  },
  {
    id_item: 1,
    name: "Agua epura 2lt",
    price: 55,
    picture: "/assets/Seven_Epura.jpg",
    details: "",
    store: "7 Eleven",
    categories: [],
  },
  {
    id_item: 2,
    name: "7 Select Papas Caseras",
    price: 25,
    picture: "/assets/Seven_PapasCaseras.jpg",
    details: "",
    store: "7 Eleven",
    categories: [],
  },
  {
    id_item: 3,
    name: "Sopa Nissin sabor Pollo",
    price: 13,
    picture: "/assets/Seven_Nissin.jpg",
    details: "",
    store: "7 Eleven",
    categories: [],
  },
  {
    id_item: 4,
    name: "Capuchino",
    price: 40,
    picture: "/assets/TimHortons_Capuccino.jpg",
    details: "",
    store: "Tim Hortons",
    categories: [],
  },
  {
    id_item: 5,
    name: "Dark Roast",
    price: 50,
    picture: "/assets/TimHortons_DarkRoast.jpg",
    details: "",
    store: "Tim Hortons",
    categories: [],
  },
  {
    id_item: 6,
    name: "Café helado original caliente",
    price: 25,
    picture: "/assets/TimHortons_CafeHelado.jpg",
    details: "",
    store: "Tim Hortons",
    categories: [],
  },
  {
    id_item: 7,
    name: "Iced Capp Supreme",
    price: 25,
    picture: "/assets/TimHortons_IcedCap.jpg",
    details: "",
    store: "Tim Hortons",
    categories: [],
  }
];

export default items
