const items = [
  {
    id_item: 0,
    name: "Coca Cola 355ml",
    price: 16,
    url: "",
    details: "",
    store: "7 Eleven",
    categories: [],
  },
  {
    id_item: 1,
    name: "Agua epura 2lt",
    price: 55,
    url: "",
    details: "",
    store: "7 Eleven",
    categories: [],
  },
  {
    id_item: 2,
    name: "Baguette Carnes Frias",
    price: 36,
    url: "",
    details: "",
    store: "7 Eleven",
    categories: [],
  },
  {
    id_item: 3,
    name: "Capuchino",
    price: 40,
    url: "",
    details: "",
    store: "Tim Hortons",
    categories: [],
  },
  {
    id_item: 4,
    name: "Dark Roast",
    price: 50,
    url: "",
    details: "",
    store: "Tim Hortons",
    categories: [],
  },
  {
    id_item: 5,
    name: "Café original caliente",
    price: 25,
    url: "",
    details: "",
    store: "Tim Hortons",
    categories: [],
  },
];

export default items
