const items = [
  {
    id_item: 0,
    name: "Boneless",
    price: 105,
    picture: "/assets/Davilas_Boneless.jpg",
    details: "",
    store: "Davila's House",
    categories: [],
  },
  {
    id_item: 1,
    name: "Tenders",
    price: 92,
    picture: "/assets/Davilas_Tenders.jpg",
    details: "",
    store: "Davila's House",
    categories: [],
  },
  {
    id_item: 2,
    name: "Burrito de Carne Asada",
    price: 98,
    picture: "/assets/Davilas_Burrito.jpg",
    details: "",
    store: "Davila's House",
    categories: [],
  },
  {
    id_item: 3,
    name: "Tacos de Carne Asada",
    price: 92,
    picture: "/assets/Davilas_TacosCarne.jpeg",
    details: "",
    store: "Davila's House",
    categories: [],
  },
  {
    id_item: 4,
    name: "Capuchino",
    price: 40,
    picture: "/assets/TimHortons_Capuccino.jpg",
    details: "",
    store: "Tim Hortons",
    categories: [],
  },
  {
    id_item: 5,
    name: "Dark Roast",
    price: 50,
    picture: "/assets/TimHortons_DarkRoast.jpg",
    details: "",
    store: "Tim Hortons",
    categories: [],
  },
  {
    id_item: 6,
    name: "Café helado original caliente",
    price: 25,
    picture: "/assets/TimHortons_CafeHelado.jpg",
    details: "",
    store: "Tim Hortons",
    categories: [],
  },
  {
    id_item: 7,
    name: "Iced Capp Supreme",
    price: 25,
    picture: "/assets/TimHortons_IcedCap.jpg",
    details: "",
    store: "Tim Hortons",
    categories: [],
  }
];

export default items
